# Pipeline for apig staging

trigger: none

pool:
  vmImage: ubuntu-latest

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

# Checkout repository
variables:
- group: wm_test_apigw_staging

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- bash: |
    echo "##vso[task.setvariable variable=target_environment]dev_environment_demo.json"
  condition: and(succeeded(), eq(variables['target_type'], 'DEV'))

- bash: |
    echo "##vso[task.setvariable variable=target_environment]stage_environment_demo.json"
  condition: and(succeeded(), eq(variables['target_type'], 'STAGE'))

- bash: |
    echo "##vso[task.setvariable variable=target_environment]prod_environment_demo.json"
  condition: and(succeeded(), eq(variables['target_type'], 'PROD'))

- template: /pipelines/api-deploy-template.yml  # Template reference
  parameters:
    apiProject: $(apiProject)
    build_environment: build_environment_demo.json
    target_environment: $(target_environment)
    target_type: $(target_type)
    prep_condition: in(variables['target_type'], 'STAGE', 'PROD')
    test_condition: in(variables['target_type'], 'STAGE', 'PROD')