# Pipeline for apig staging

trigger: none

pool:
  vmImage: ubuntu-latest

# To do: Add apiProject as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: apiProject
#   type: string
#   default: 'petstore'

variables:
- group: wm_test_apigw_staging

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- template: /pipelines/api-deploy-template.yml  # Template reference
  parameters:
    apiProject: $(apiProject)
    build_environment: build_environment_demo.json
    target_environment: stage_environment_demo.json
    target_type: STAGE
    prep_condition: ${{true}}
    test_condition: ${{true}}