# Pipeline for apig staging

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: apiProject
  type: string
  default: Usecases
  values:
  - Usecases
  - Associate policyactions and application with API
  - API with Custom Extension Policy
  - API with Scope Policy
  - OAuth2 API with scope mapping and application
- name: apiName
  type: string
  default: 'Petstore'
- name: apiVersion
  type: string
  default: '1.0'

variables:
- group: wm_test_apigw_staging

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"

- template: /pipelines/api-create-template.yml  # Template reference
  parameters:
    apiProject: '${{parameters.apiProject}}'
    apiName: '${{parameters.apiName}}'
    apiVersion: '${{parameters.apiVersion}}'
    environment: thesdev_environment.json
    type: DEV